import type { Game } from 'types/global'
import Head from 'next/head'
import { GetServerSideProps } from 'next'

type Props = {
  game: Game,
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const gameId: string = context.query['id'] as string
  const res = await fetch(`http://api:3000/api/v1/games/${gameId}`)
  if (res.status == 200) {
    const json = await res.json()
    if (json.ok) return { props: { game: json.data } }
  }
  return {
    props: {},
    redirect: { statusCode: 302, destination: '/' }
  }
}

const Games = (props: Props) => {
  return (
    <main id='main'>
      <Head>
        <title>{ props.game?.title} | WORDLE MAKER APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container'>
        <h1 className='title'>{ props.game?.title }</h1>
      </div>
    </main>
  )
}

export default Games
