import type { Game } from 'types/global'
import Head from 'next/head'
import { GetServerSideProps } from 'next'

type Props = {
  game: Game,
  words: String[],
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const id: string = context.query['id'] as string
  const reses = await Promise.all([
    fetch(`http://api:3000/api/v1/games/${id}`),
    fetch(`http://api:3000/api/v1/games/${id}/word_list`)
  ])
  if (reses[0].status == 200 && reses[1].status == 200) {
    const jsons = await Promise.all([reses[0].json(), reses[1].json()])
    if (jsons[0].ok) return { props: { game: jsons[0].data, words: jsons[1].data } }
  }
  return { notFound: true }
}

const Games = (props: Props) => {
  return (
    <main id='main'>
      <Head>
        <title>{ props.game?.title} | WORDLE MAKER APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container'>
        <h1 className='title'>{ props.game?.title }</h1>
      </div>
    </main>
  )
}

export default Games
