import type { Game, Word } from 'types/global'
import Head from 'next/head'
import { GetServerSideProps } from 'next'
import { useState } from 'react'
import { useKeyDown } from 'hooks/useKeyDown'

import Language from 'scripts/language'

type Props = {
  game: Game,
  wordList: String[],
  wordToday: Word,
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const id: string = context.query['id'] as string
  const reses = await Promise.all([
    fetch(`http://api:3000/api/v1/games/${id}`),
    fetch(`http://api:3000/api/v1/games/${id}/word_list`),
    fetch(`http://api:3000/api/v1/words/today/${id}`),
  ])
  if (reses[0].status == 200 && reses[1].status == 200 && reses[2].status == 200) {
    const jsons = await Promise.all([reses[0].json(), reses[1].json(), reses[2].json()])
    if (jsons[0].ok && jsons[1].ok && jsons[2].ok) {
      return { props: { game: jsons[0].data, wordList: jsons[1].data, wordToday: jsons[2].data } }
    }
  }
  return { notFound: true }
}

const Games = (props: Props) => {
  const [inputtedWordList, setInputtedWordList] = useState<string[][]>([])
  const [currentWord, setCurrentWord] = useState<string[]>([])
  const language = new Language(props.game.lang)
  const CHALENGE_COUNT = 6

  useKeyDown((event) => handleInputKey(event.key))

  function handleInputKey(key: string): void{
    if (key == 'Enter') {
      setCurrentWord(prevCurrentWord => {
        if (prevCurrentWord.length == props.game.char_count) {
          setInputtedWordList(prevInputtedWordList => {
            if (CHALENGE_COUNT >= prevInputtedWordList.length) {
              return [...prevInputtedWordList, prevCurrentWord]
            } else {
              return prevInputtedWordList
            }
          })
          return []
        } else {
          return prevCurrentWord
        }
      })
    }else if (key == 'Backspace') {
      setCurrentWord(prevCurrentWord => {
        return prevCurrentWord.slice(0, prevCurrentWord.length - 1)
      })
    } else if (language.regexp?.test(key) && key.length == 1) {
      setCurrentWord(prevCurrentWord => {
        if (prevCurrentWord.length < props.game.char_count) {
          return prevCurrentWord.concat(key)
        } else {
          return prevCurrentWord
        }
      })
    }
  }

  return (
    <main id='main'>
      <Head>
        <title>{ props.game?.title} | WORDLE MAKER APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container'>
        <h1 className='title'>{props.game?.title}</h1>
        <p>{props.wordToday.name}</p>
      </div>
    </main>
  )
}

export default Games
