import { useRouter } from 'next/router'
import { useState, useContext, useRef } from 'react'
import { useAlert } from 'react-alert'

import useSignOut from 'hooks/useSignOut'

import Head from 'next/head'
import nprogress from 'nprogress'

import SlideoutMenu from 'components/slideout_menu'
import Sidemenu from 'components/sidemenu'
import LoadingOverlay from 'components/loading_overlay'

import validate from 'scripts/validate'

import CurrentTokenContext from 'contexts/current_token'

const MygamesCreate = () => {
  /********** State **********/
  const [title, setTitle] = useState<string>('')
  const [desc, setDesc] = useState<string>('')
  const [lang, setLang] = useState<string>('en')
  const [challengeCount, setChallengeCount] = useState<number>(6)
  const [charCount, setCharCount] = useState<number>(5)
  const [showOverlay, setShowOverlay] = useState<boolean>(false)
  /*********** Ref ***********/
  const inputTitleEl = useRef<HTMLInputElement>(null)
  const divTitleInvalidEl = useRef<HTMLDivElement>(null)
  const selectLangEl = useRef<HTMLSelectElement>(null)
  /********* Context *********/
  const currentTokenContext = useContext(CurrentTokenContext)

  const signOut = useSignOut()
  const router = useRouter()
  const alert = useAlert()

  function validateTitle(): boolean{
    const titleLength: number = Number(title.length)
    if (titleLength < 1) {
      inputTitleEl.current?.classList.add('input-invalid')
      if (divTitleInvalidEl.current) divTitleInvalidEl.current.innerHTML = '* Title is required.'
      return false
    } else if (titleLength > 100) {
      inputTitleEl.current?.classList.add('input-invalid')
      if (divTitleInvalidEl.current) divTitleInvalidEl.current.innerHTML = '* Title must be 100 characters or less.'
      return false
    } else {
      inputTitleEl.current?.classList.remove('input-invalid')
      if (divTitleInvalidEl.current) divTitleInvalidEl.current.innerHTML = ''
      return true
    }
  }

  function handleClickSubmit(): void{
    if (validate.token(currentTokenContext.currentToken)) {
      if (validateTitle()) {
        const body = {
          game: {
            'title': title,
            'desc': desc,
            'challenge_count': challengeCount,
            'char_count': charCount,
            'lang': lang
          }
        }
        setShowOverlay(true)
        nprogress.start()
        fetch('http://localhost:3000/api/v1/games', {
          method: 'POST',
          headers: {
            "Content-Type": "application/json",
            'access-token': currentTokenContext.currentToken.accessToken,
            'client': currentTokenContext.currentToken.client,
            'uid': currentTokenContext.currentToken.uid
          },
          body: JSON.stringify(body)
        }).then(res => res.json())
          .then(json => {
            if (json.ok) {
              alert.show('CREATED', {type: 'success'})
              router.push(`/mygames/edit/${json.data.id}#add-words`)
            } else {
              alert.show(json.message, {type: 'error'})
              console.error(json)
              setShowOverlay(false)
            }
          })
          .catch(error => {
            console.error(error)
            setShowOverlay(false)
          })
          .finally(() => { nprogress.done() })
      }
    } else {
      signOut(() => router.replace('/signup'))
    }
  }

  return (
    <main id='main'>
      <Head>
        <title>My Games | WORDLE MAKER APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SlideoutMenu />

      <div className='container'>
        <div id='sidemenu-container'>
          {/* Sidemenu */}
          <Sidemenu activeMenu={'create' }/>
          {/* Main */}
          <div id='sidemenu-main'>
            <div className='title'>
              <div className='title-text'>Create a game</div>
            </div>

            {/* Game Form */}
            <form id='game-form' className='sp-padding' onSubmit={e => e.preventDefault()}>
              {/* Title */}
              <div className='form-group'>
                <label>Title</label>
                <div className='form-countable-input-group'>
                  <input ref={inputTitleEl} id='game-title' type='text' maxLength={100} value={title} onChange={e => setTitle(e.target.value)} />
                  <div className='form-countable-input-counter'>{`${title.length} / 100`}</div>
                </div>
                <div ref={divTitleInvalidEl} id='game-title-invalid-feedback' className='form-group-invalid-feedback'></div>
              </div>
              {/* Description */}
              <div className='form-group'>
                <label>Description</label>
                <div className='form-countable-input-group'>
                  <textarea id='game-desc' rows={3} maxLength={200} value={desc} onChange={e => setDesc(e.target.value)} />
                  <div className='form-countable-input-counter'>{`${desc.length} / 200`}</div>
                </div>
                <div id='game-title-invalid-feedback' className='form-group-invalid-feedback'></div>
              </div>
              {/* Challenge count */}
              <div className='form-group'>
                <label>Challenge count</label>
                <select id='game-challengeount' value={challengeCount} onChange={e => setChallengeCount(Number(e.target.value))}>
                  <option value='2'>2</option>
                  <option value='3'>3</option>
                  <option value='4'>4</option>
                  <option value='5'>5</option>
                  <option value='6'>6</option>
                  <option value='7'>7</option>
                  <option value='8'>8</option>
                  <option value='9'>9</option>
                  <option value='10'>10</option>
                </select>
              </div>
              {/* Character count */}
              <div className='form-group'>
                <label>Character count</label>
                <select id='game-charcount' value={charCount} onChange={e => setCharCount(Number(e.target.value))}>
                  <option value='2'>2</option>
                  <option value='3'>3</option>
                  <option value='4'>4</option>
                  <option value='5'>5</option>
                  <option value='6'>6</option>
                  <option value='7'>7</option>
                  <option value='8'>8</option>
                  <option value='9'>9</option>
                  <option value='10'>10</option>
                </select>
              </div>
              {/* Language */}
              <div className='form-group'>
                <label>Language</label>
                <select ref={selectLangEl} id='game-lang' value={lang} onChange={e => setLang(e.target.value)}>
                  <option value='en'>English</option>
                  <option value='ja'>Japanese</option>
                </select>
              </div>
              {/* Submit */}
              <button type='button' id='game-submit' className='btn btn-primary' disabled={title.length < 1 || title.length > 100} onClick={handleClickSubmit}>Submit</button>
            </form>
            <LoadingOverlay showOverlay={showOverlay} />
          </div>
        </div>
      </div>
    </main>
  )
}

export default MygamesCreate
