import Head from 'next/head'

export default function Custom404(){
  return (
    <main id='main'>
      <Head>
        <title>404 Not Found | WORDLE MAKER APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container'>
        <h1>404 Not Found</h1>
        <p>Oops! The game was not found..</p>
      </div>
    </main>
  )
}