import Head from 'next/head'

import SlideoutMenu from 'components/slideout_menu'

export default function Custom404(){
  return (
    <main id='main'>
      <Head>
        <title>404 Not Found | WORDLE MAKER APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SlideoutMenu />

      <div className='container'>
        <div className='text'>
          <h1>404 Not Found</h1>
          <p>Oops! This game you're looking for is not found or suspended for some reasons...</p>
        </div>
      </div>
    </main>
  )
}