import { NextPageContext } from 'next';
import Head from 'next/head'

interface Props {
	statusCode?: number;
}

function Error({ statusCode }: Props): JSX.Element {
  return (
    <main id='main'>
      <Head>
        <title>`${statusCode} | WORDLE MAKER APP`</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container'>
        <h1>500</h1>
        <p>
          {statusCode
            ? `An error ${statusCode} occurred on server`
            : 'An error occurred on client'}
        </p>
      </div>
    </main>
  )
}

Error.getInitialProps = ({ res, err }: NextPageContext) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404
  return { statusCode }
}

export default Error
