import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {

  return (
    <main id='main'>
      <div className='container'>
        <Head>
          <title>WORDLE MAKER APP</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className='title'>
          Index.tsx
        </h1>
      </div>
    </main>
  )
}

export default Home
