import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Signup.module.css'

const Signup: NextPage = () => {
  return (
    <main className='main'>
      <div className='container'>
        <Head>
          <title>Signup | WORDLE MAKER APP</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className='title'>
          Signup.tsx
        </h1>
      </div>
    </main>
  )
}

export default Signup