import type { Token } from 'types/global'
import { useRouter } from 'next/router'
import { useState, useMemo, useContext } from 'react'
import { useAlert } from 'react-alert'
import { useSignOut } from 'hooks/useSignOut'
import nprogress from 'nprogress'

import Head from 'next/head'

import Sidemenu from 'components/sidemenu'
import Modal from 'components/modal'
import LoadingOverlay from 'components/loading_overlay'

import validate from 'scripts/validate'

import CurrentTokenContext from 'contexts/current_token'

const Account = () => {
  const [showOverlay, setShowOverlay] = useState<boolean>(false)
  const currentTokenContext = useContext(CurrentTokenContext)
  const [checkedConfirmation, setCheckedConfirmation] = useState<boolean | undefined>(false)
  const [showModal, setShowModal] = useState<boolean>(false)
  const handleConfirmation = useMemo(() => {
    return () => {
      setCheckedConfirmation(!checkedConfirmation);
    }
  }, [checkedConfirmation])
  const router = useRouter()
  const alert = useAlert()
  const signOut = useSignOut()

  async function fetchDeleteAccount(token: Token) {
    const res = await fetch('http://localhost:3000/api/v1/auth/', {
      method: 'DELETE',
      headers: {
        'access-token': token.accessToken,
        'client': token.client,
        'uid': token.uid
      }
    })
    return await res.json()
  }

  function handleClickDeleteAccount(): void{
    if (validate.token(currentTokenContext.currentToken)) {
      setShowOverlay(true)
      nprogress.start()
      fetchDeleteAccount(currentTokenContext.currentToken).then(json => {
        if (json.status == 'success') {
          signOut(() => {
            alert.show('DELETED', {type: 'success'})
            router.replace('/')
          })
        } else {
          alert.show('FAILED', {type: 'error'})
          console.error('Error', json)
        }
      }).catch(error => {
        console.log(error)
        setShowOverlay(false)
      }).finally(() => { nprogress.done() })
    }
  }

  return (
    <main id='main'>
      <Head>
        <title>Account | WORDLE MAKER APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Modal */}
      <Modal showModal={showModal} setShowModal={setShowModal}>
        <div className='modal-window-container'>
          <div className='modal-window-header'>
            Delete Account
          </div>
          <div className='modal-window-body'>
            <p>Are you sure?</p>
            <ol>
              <li>Your account and related information will be deleted.</li>
              <li>We can't recover your account and related information you deleted.</li>
              <li>If you send an inquiry to us about it, We can't reply to you.</li>
            </ol>
            <div>
            <input type="checkbox" id="confirmation" checked={checkedConfirmation} onChange={handleConfirmation} />
            <label>I agree.</label>
          </div>
          </div>
          <div className='modal-window-footer'>
            <button className='btn btn-danger' onClick={handleClickDeleteAccount} disabled={!checkedConfirmation}>Delete Account</button>
            <button className='btn btn-default' onClick={()=>setShowModal(false)}>Close</button>
          </div>
        </div>
      </Modal>

      <LoadingOverlay showOverlay={showOverlay} />

      <div className='container'>
        <div id='sidemenu-container'>
          {/* Sidemenu */}
          <Sidemenu activeMenu={'account'} />

          {/* Main */}
          <div id='sidemenu-main'>
            <h1 className='title'>Account</h1>
            <button className='btn btn-danger' onClick={() => { setShowModal(true) }}>Delete Account</button>
          </div>
        </div>
      </div>
    </main>
  )
}

export default Account
